const $=id=>document.getElementById(id);
const state={yours:null,ref:null,punches:[],sections:[]};
const fmt=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'—';
const db=x=>20*Math.log10(Math.max(x,1e-9));
function synthProfile(kind){const n=240,energy=[],bright=[];for(let i=0;i<n;i++){const t=i/n;let e=0.22+0.05*Math.sin(t*18);if(t>0.18&&t<0.32)e=0.42;if(t>0.38&&t<0.58)e=0.6;if(t>0.62&&t<0.78)e=0.72;if(t>0.86)e=0.16;if(kind==='yours'){e*=(t>0.38&&t<0.58)?0.72:0.9;bright.push(1800+400*e);}else bright.push(2400+900*e);energy.push(e);}return{name:kind==='yours'?'demo-bounce.wav':'demo-reference.wav',duration:kind==='yours'?187:193,peak:kind==='yours'?0.91:0.98,rms:kind==='yours'?0.118:0.162,crest:kind==='yours'?17.7:15.6,centroid:kind==='yours'?1980:2860,energy,bright};}
async function analyzeFile(file){const ctx=new(window.AudioContext||window.webkitAudioContext)();const audio=await ctx.decodeAudioData(await file.arrayBuffer());const ch=audio.getChannelData(0);const n=ch.length,hop=Math.max(1,Math.floor(n/240));const energy=[],bright=[];let peak=0,sumSq=0;for(let i=0;i<n;i++){const a=Math.abs(ch[i]);if(a>peak)peak=a;sumSq+=ch[i]*ch[i];}const rms=Math.sqrt(sumSq/n);for(let b=0;b<240;b++){const start=b*hop;let e=0,wsum=0,csum=0;const slice=Math.min(hop,n-start);for(let i=0;i<slice;i+=4)e+=ch[start+i]**2;energy.push(Math.sqrt(e/Math.max(slice/4,1)));for(let i=8;i<slice;i+=8){const d=ch[start+i]-ch[start+i-8];wsum+=d*d;csum+=ch[start+i]**2;}bright.push(800+6000*(wsum/Math.max(csum,1e-8)));}return{name:file.name,duration:audio.duration,peak,rms,crest:db(peak)-db(rms),centroid:bright.reduce((a,b)=>a+b,0)/bright.length,energy,bright};}
function draw(){const canvas=$('wave');const w=canvas.width=canvas.clientWidth*2;const h=canvas.height=360;const g=canvas.getContext('2d');g.fillStyle='#0e1016';g.fillRect(0,0,w,h);const curve=(p,c)=>{if(!p)return;const arr=p.energy,max=Math.max(...arr,0.001);g.beginPath();arr.forEach((v,i)=>{const x=(i/(arr.length-1))*w,y=h-(v/max)*(h*0.86)-12;i?g.lineTo(x,y):g.moveTo(x,y);});g.strokeStyle=c;g.lineWidth=3;g.stroke();};curve(state.ref,'#3ec6ff');curve(state.yours,'#ff5a36');g.font='20px monospace';g.fillStyle='#ff5a36';g.fillText('YOURS',24,36);g.fillStyle='#3ec6ff';g.fillText('REF',140,36);}
function guessSections(p){if(!p)return[];const e=p.energy,max=Math.max(...e),labels=[];let last='';e.forEach((v,i)=>{const nrm=v/max;let name='Break / verse';if(i<e.length*0.08)name='Intro';else if(nrm>0.78)name='Drop / chorus peak';else if(nrm>0.55)name='Chorus';else if(nrm<0.22&&i>e.length*0.8)name='Outro';if(name!==last){last=name;labels.push({name,t:(i/e.length)*p.duration});}});return labels.slice(0,8);}
function buildPunches(){const y=state.yours,r=state.ref,list=[];if(!y||!r){state.punches=[];return;}const loud=db(r.rms)-db(y.rms);if(loud>1.2)list.push(`Integrated level is ${fmt(loud)} dB quieter than the reference. Ride the chorus before the limiter.`);else if(loud<-1.2)list.push(`You are ${fmt(-loud)} dB hotter than the reference.`);else list.push('Overall loudness is close.');const bd=r.centroid-y.centroid;if(bd>350)list.push(`Top end is dull (centroid ${fmt(y.centroid,0)} vs ${fmt(r.centroid,0)} Hz). Add air after 8k.`);else if(bd<-350)list.push('Yours is brighter than the reference. Tame 6-10 kHz.');else list.push('Brightness is in the same neighborhood.');if(y.crest-r.crest>2)list.push(`Yours is ${fmt(y.crest-r.crest)} dB more dynamic. Compress the hook bus.`);if(r.crest-y.crest>2)list.push('Yours is flatter than the reference. Ease the master.');list.push('Export notes into MixForge or DAW markers. Do not regenerate the whole song unless structure is the problem.');state.punches=list;state.sections=guessSections(y);}
function render(){draw();const s=$('stats');s.innerHTML=(!state.yours&&!state.ref)?'<p class="muted">Load two files or tap Load demo session.</p>':[state.yours,state.ref].filter(Boolean).map(p=>`<p>${p.name}<br>len ${fmt(p.duration,0)}s · peak ${fmt(db(p.peak))} dBFS · RMS ${fmt(db(p.rms))} dBFS · crest ${fmt(p.crest)} dB</p>`).join('');$('punches').innerHTML=state.punches.map(p=>`<li>${p}</li>`).join('')||'<li>Punch list appears after both sides load.</li>';$('sections').innerHTML=state.sections.map(s=>`<span class="sec">${s.name} · ${fmt(s.t,0)}s</span>`).join('')||'—';}
async function onFile(slot,file){if(!file)return;$(slot==='yours'?'name-yours':'name-ref').textContent=file.name;try{state[slot]=await analyzeFile(file);buildPunches();render();}catch(e){alert('Could not decode that audio file.');}}
$('file-yours').addEventListener('change',e=>onFile('yours',e.target.files[0]));
$('file-ref').addEventListener('change',e=>onFile('ref',e.target.files[0]));
$('load-demo').addEventListener('click',()=>{state.yours=synthProfile('yours');state.ref=synthProfile('ref');$('name-yours').textContent=state.yours.name;$('name-ref').textContent=state.ref.name;buildPunches();render();document.getElementById('studio').scrollIntoView({behavior:'smooth'});});
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=name;a.click();}
$('export-txt').addEventListener('click',()=>{if(!state.punches.length)return alert('Run a comparison first.');download('refpunch-notes.txt',['REFPUNCH MIX NOTES',state.yours.name+' vs '+state.ref.name,'',...state.punches.map((p,i)=>`${i+1}. ${p}`)].join('\n'));});
$('export-json').addEventListener('click',()=>{if(!state.punches.length)return alert('Run a comparison first.');download('refpunch-session.json',JSON.stringify({punches:state.punches,sections:state.sections,yours:state.yours.name,ref:state.ref.name},null,2));});
render();
